on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Publish .NET Core Project
      run: dotnet publish -c Release --nologo

    - name: Test
      run: ls && pwd

   # - name: Change base-tag in index.html from / to Base URL
   #   run: sed -i 's/<base href="\/" \/>/<base href="\/Ari-Qu3sadillas.github.io\/" \/>/g' Profile/bin/Release/net8.0/publish/wwwroot/index.html

    - name: Copy index to 404
      run: cp Profile/bin/Release/net8.0/publish/wwwroot/index.html Profile/bin/Release/net8.0/publish/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch Profile/bin/Release/net8.0/publish/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: Profile/bin/Release/net8.0/publish/wwwroot
